learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

# TEMPLATE TAGGING
# setting namespace whenever you're using template tagging
# Global variable where Django automatically look for it
app_name = 'basic_app'
# this statement will tell Django to look under the basic_app
# and find url that matches

urlpatterns = [
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls'))
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world', 'number':100}
    return render(request, 'basic_app/index.html', context_dict)

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-expand-lg navbar-light navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
          <li><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="nav-link" href="{% url 'basic_app:other' %}">Other</a></li>
        </ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inherited if you extend! -->
      {% endblock %}
    </div>
  </body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% load my_extras %}
  {% block body_block %}
    <h1>Welcome to Index</h1>
    <h2>This is index.html page showing!</h2>
    <h1>{{ text|cut:'world' }}</h1>
    <h1>{{ number|add:"99" }}</h1>
  {% endblock %}
<!-- <html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to INDEX</h1>

  </body>
</html> -->

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>Welcome to Other!</h1>
    <h2>This is an example of template inheritance!</h2>
  {% endblock %}
<!-- <html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to OTHER!</h1>

  </body>
</html> -->

learning_templates/templates/basic_app/relative_url_templates.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1>Welcome to Relative URL Templates</h1>
    <!-- <a href="basic_app/other.html">THE OTHER PAGE</a> -->
    <a href="{% url 'basic_app:other' %}">THE OTHER PAGE</a>
    <!-- Here basic_app is from app_name = 'basic_app' in basic_app/urls.py
    and other is from path('other/', views.other, name='other')
    in basic_app/urls.py
    There should not be space in the string 'basic_app:other'
    defined in template tagging-->

    <!--Below is way to add admin page to an anchor tag
    In settings.py of project folder, we not ony have basic_app
    but also django.contrib.admin app which is always imported
    as an installed application.
    But inside admin app there is its own urls.py file
    there is an admin application with index named view    -->
    <a href="{% url 'admin:index' %}">LINK TO ADMIN</a>
    <!-- Inorder for this to work sometimes we have to make migrations  -->.

    <a href="{% url 'index' %}">LINK TO INDEX</a>

  </body>
</html>